languageCode = 'en-us'
title = "Midwest Tech Conference"

theme = "hugo-coder"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  mainTitle = "MWTC"
  subtitle = "Midwest Tech Conference"
  eventDate = "November 8th, 2025"
  eventTime = "8am to 5pm"
  eventLocation = "Westminster College, Fulton, MO"
  description = "A tech conference for the people"
  keywords = "MWTC, Midwest, Tech, Conference, Technical"
  logo = "images/MWTC_dark.png"
  faviconSVG = "/images/favicon.svg"
  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2025
  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false

  customSCSS = ['scss/logo.scss']

[[params.links]]
  name = "Westminster College, Champ Auditorium"
  icon = "fa fa-2x fa-map-marker"
  weight = 1
  url = "https://maps.app.goo.gl/2GBPMJxK4S7DCVs39"

#[[params.links]]
#  name = "Call for Papers"
#  icon = "fa fa-2x fa-commenting"
#  weight = 2
#  url = "https://sessionize.com/mwtc"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[[menu.main]]
  name = "Register now!"
  weight = 1
  url = "https://www.eventbrite.com/e/midwest-tech-conference-2025-tickets-1405626569909"
  target = "_blank"
[[menu.main]]
  name = "Schedule"
  weight = 2
  url = "schedule"
[[menu.main]]
  name = "Sponsors"
  weight = 20
  url = "sponsors"
[[menu.main]]
  name = "About"
  weight = 50
  url = "about"
[[menu.main]]
  name = "FAQ"
  weight = 99
  url = "faq"
