languageCode = 'en-us'
title = "Midwest Tech Conference"

theme = "hugo-coder"
defaultcontentlanguage = "en"

[build]
hugo_version = "0.149.0"

[pagination]
pagerSize = 20

[markup.highlight]
#style = "github-dark"
style = "monokai"

[params]
  mainTitle = "MWTC"
  subtitle = "Midwest Tech Conference"
  eventDate = "October 7th, 2026"
  eventTime = "8am to 5pm"
  eventLocation = "Location TBD"
  description = "A tech conference for the people"
  keywords = "MWTC, Midwest, Tech, Conference, Technical"
  logo = "images/MWTC_dark.png"
  faviconSVG = "/images/favicon.svg"
  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2025
  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false

  customSCSS = ['scss/variables.scss', 'scss/logo.scss', 'scss/article.scss', 'scss/hero.scss', 'scss/pages.scss']
  customJS = ['js/countdown.js']

#[[params.links]]
#  name = "Westminster College, Champ Auditorium"
#  icon = "fa fa-2x fa-map-marker"
#  weight = 1
#  url = "https://maps.app.goo.gl/2GBPMJxK4S7DCVs39"

#[[params.links]]
#  name = "Call for Papers"
#  icon = "fa fa-2x fa-commenting"
#  weight = 2
#  url = "https://sessionize.com/mwtc"

[[params.valueProps]]
  icon   = "fa-solid fa-ticket"
  strong = "$10"
  span   = "Free for students"

[[params.valueProps]]
  icon   = "fa-solid fa-microphone"
  strong = "8+ Sessions"
  span   = "Talks & workshops"

[[params.valueProps]]
  icon   = "fa-solid fa-people-group"
  strong = "All Are Welcome"
  span   = "Enthusiasts to experts"

[[params.valueProps]]
  icon   = "fa-solid fa-heart"
  strong = "Volunteer-Run"
  span   = "Community powered"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[[menu.main]]
  name = "Tickets on sale May 1st!"
  weight = 1
  url = "https://www.eventbrite.com/e/mid-west-tech-conference-2026-tickets-1983590577815"
  target = "_blank"
[[menu.main]]
  name = "Schedule"
  weight = 2
  url = "schedule"
[[menu.main]]
  name = "Sponsors"
  weight = 20
  url = "sponsors"
[[menu.main]]
  name = "About"
  weight = 50
  url = "about"
[[menu.main]]
  name = "FAQ"
  weight = 99
  url = "faq"
